// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB54Gz5EVU1VLpTp-dk85X6cMJzevorF70',
    appId: '1:356447967867:web:e8c8ffa1f4bf22ec2320de',
    messagingSenderId: '356447967867',
    projectId: 'elearn-cb964',
    authDomain: 'elearn-cb964.firebaseapp.com',
    databaseURL: 'https://elearn-cb964-default-rtdb.firebaseio.com',
    storageBucket: 'elearn-cb964.appspot.com',
    measurementId: 'G-H0RLZ4LCRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOKss0toGE128VA-WcQDlXVJqhVDOCwd0',
    appId: '1:356447967867:android:fc91dd2d71540f212320de',
    messagingSenderId: '356447967867',
    projectId: 'elearn-cb964',
    databaseURL: 'https://elearn-cb964-default-rtdb.firebaseio.com',
    storageBucket: 'elearn-cb964.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHZMUmiHmIvVf5BiskxsMHEehgWvOXGnc',
    appId: '1:356447967867:ios:e08f6a57b833d0732320de',
    messagingSenderId: '356447967867',
    projectId: 'elearn-cb964',
    databaseURL: 'https://elearn-cb964-default-rtdb.firebaseio.com',
    storageBucket: 'elearn-cb964.appspot.com',
    iosClientId: '356447967867-9v1da4q8883c1mj24rn18ive09qs68gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodSpaceTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXHgezals71-LhpxU-VqsdLLlX_UJcRBI',
    appId: '1:356447967867:web:f453e3455efb05262320de',
    messagingSenderId: '356447967867',
    projectId: 'elearn-cb964',
    authDomain: 'elearn-cb964.firebaseapp.com',
    databaseURL: 'https://elearn-cb964-default-rtdb.firebaseio.com',
    storageBucket: 'elearn-cb964.appspot.com',
    measurementId: 'G-V78KWH9SW3',
  );
}
